apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: crash-looping-pod
  namespace: ns1
spec:
  groups:
  - name: crash-looping-pod
    rules:
    - alert: CrashLoopingPods
      expr: increase(kube_pod_container_status_restarts_total[1m]) > 3
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: Container CPU usage (instance {{ $labels.instance }})
        description: "Container CPU usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
